config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: "opportunities#index"
  
  resources :opportunities do
    resources :comments, only: :create
  end 
   resources :users, only: [:index ,:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions 

  belongs_to :user
  belongs_to :opportunity
  belongs_to :kind

  validates :text, :kind, presence: true
  validates :kind_id , numericality: { other_than: 1 }
end

app/models/kind.rb
class Kind < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'アドバイス' },
    { id: 3, name: '応援コメント' },
    { id: 4, name: 'フィードバック' },
  ]

  include ActiveHash::Associations
  has_many :comments
  has_many :opportunities
end

app/models/motivation.rb
class Motivation < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '案内前' },
    { id: 3, name: '案内後' },
    { id: 4, name: '前向き検討' },
    { id: 5, name: '保留中' },
    { id: 6, name: '要追客' },
    { id: 7, name: 'ほぼ決まる' },
  ]

  include ActiveHash::Associations
  has_many :opportunities

end

app/models/opportunity.rb
class Opportunity < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  belongs_to :phase 
  belongs_to :kind
  belongs_to :motivation
  has_one_attached :image
  has_many :comments

  with_options presence: true do
    validates :title
    validates :bottle_neck, length: { maximum: 150 }
    validates :next_action,length: { maximum: 150 }
  end
  with_options numericality: { other_than: 1 } do
    validates :phase_id
    validates :motivation_id
  end
end

app/models/phase.rb
class Phase < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '案内前' },
    { id: 3, name: '案内後' },
    { id: 4, name: '前向き検討中' },
    { id: 5, name: '保留中' },
    { id: 6, name: '要追客' },
    { id: 7, name: 'ほぼ決まる' },
  ]

  include ActiveHash::Associations
  has_many :opportunities

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :name, presence: true
  validates :profile, presence: true
  validates :position, presence: true
  validates :image, presence: true
  
  has_many :opportunities
  has_one_attached :image
  has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile, :position,:image])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
   def create
    @comment = Comment.new(comment_params)
     if @comment.save
      redirect_to opportunity_path(@comment.opportunity)
    else
     @opportunity = @comment.opportunity
     @comments = @opportunity.comments
     render "opportunities/show"
   end
  end
 
  private

  def comment_params
    params.require(:comment).permit(:text,:kind_id).merge(user_id: current_user.id, opportunity_id: params[:opportunity_id])
  end
end

app/controllers/opportunities_controller.rb
class OpportunitiesController < ApplicationController
  before_action :set_opportunity, except: [:index, :new, :create]

  def index
    @opportunities = Opportunity.includes(:user)
  end

  def new
    @opportunity = Opportunity.new
  end 

  def create
    @opportunity = Opportunity.new(opportunity_params)
    if @opportunity.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @opportunity = Opportunity.find(params[:id])
    @comment = Comment.new
    @comments = @opportunity.comments
  end

  def edit
    @opportunity = Opportunity.find(params[:id])
  end

  def update
    if @opportunity.update(opportunity_params)
      redirect_to root_path
    else
      render :show
    end
  end

  private

  def opportunity_params
    params.require(:opportunity).permit(:title, :bottle_neck, :next_action, :phase_id, :motivation_id).merge(user_id: current_user.id)
  end

  def set_opportunity
    @opportunity = Opportunity.find(params[:id])
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
 
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/opportunities_helper.rb
module OpportunitiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.erb
<% if @opportunity.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>商談グラム</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %> 
          </div>
          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
              <%= link_to "商談投稿" , new_opportunity_path, class: :nav__btn %>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © Syoudan gram All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/opportunities/_opportunity.html.erb
<div class="card">

  <div class="card__body">
     <%= link_to opportunity.title, opportunity_path(opportunity), class: :text__title%>
      <div class="card__summary">
           <%= link_to "担当者： #{opportunity.user.name}", user_path(opportunity.user), class: :user__title %>
        <div>
         投稿日：<%= opportunity.created_at.strftime('%Y年%m月%d日') %>
         </div>
         <div>
         商談フェーズ： <%= opportunity.phase.name %>
         </div>
          <p>-----------------------------</p>
         <div class="next">
         <P>【NEXTアクション】</P>
       <%= opportunity.bottle_neck %>
        </div>
      </div>

  </div>
</div>

app/views/opportunities/_side_bar.html.erb
    
  <% if user_signed_in? %>
      <div class="greeting">
        <%= link_to "#{current_user.name}さん", user_path(current_user), class: :greeting__link%>
        <div class="side__image">
         <% if current_user.image.nil? %>
           <%= image_tag "noimage.png" %>
           <% else %>
        <%= image_tag current_user.image , class: :side__image %>
        </div>
      </div>
      <% end %>
    <% end %>

<div class="rooms"> 
   <div class="room_title">自分の商談一覧
   ( <%= current_user.opportunities.count %> ) 
    </div>
    <% current_user.opportunities.each do |opportunity| %>
    <div class="room">
      <div class="room-name">
        <%= link_to opportunity.title, opportunity_path(opportunity) %>
      </div>
    </div>
  <% end %>

  </div>

app/views/opportunities/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">プロトタイプ編集</h2>
     <%= form_with model:@opportunity, url: opportunity_path, local: true do |f| %>

        <div class="field">
          <%= f.label :title, "タイトル" %><br />
          <%= f.text_area :title,class: :form__text %>
        </div>

        <div class="field">
          <%= f.label :bottle_neck, "ネックになっている事" %><br />
          <%= f.text_area :bottle_neck, class: :form__text %>
        </div>

        <div class="field">
          <%= f.label :next_action, "次のアクション" %><br />
          <%= f.text_area :next_action, class: :form__text %>
        </div>

        <div class="field">
        <%= f.label :phase_id, "商談フェーズ" %><br />
         <%= f.collection_select(:phase_id,Phase.all, :id, :name, {}, {class:"select-box"}) %>
        </div>

         <div class="field">
        <%= f.label :motivation_id, "熱さレベル" %><br />
         <%= f.collection_select(:motivation_id,Motivation.all, :id, :name, {}, {class:"select-box"}) %>
        </div>


        <div class="actions">
          <%= f.submit "新規登録", class: :form__btn  %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/opportunities/index.html.erb
<main class="main">
  <div class="wrapper">
  <% if user_signed_in? %>
    <div class="chat-side">
        <%= render "side_bar" %>
    </div>
    <div class="chat-main">
      <h3 style="border-bottom: 1px solid #426579;border-left: 10px solid #426579;padding: 7px; margin: 3px;">KPI（Key Performance Indicator／重要業績評価指標）</h3>
       <div class="main_header">
        <div class ="date">
          <h3 style="border-bottom: 1px solid  #880088;border-left: 10px solid   #995588;padding: 7px; margin: 3px;">状況別</h3>

          <%= pie_chart Opportunity.group(:phase_id).count, id: "column-chart", width: "200px", height: "200px", colors: ["#D199FF", "#FFBA66", "#666"] %>
          
            <table class="date_table">  
            <tr>
              <th class="date__col1"></th>
              <td class="date__col2">案内前</td>
            </tr>
             <tr>
              <th class="date__col3"></th>
              <td class="date__col2">案内後</td>
            </tr>
            <tr>
              <th class="date__col4"></th>
              <td class="date__col2">前向き検討</td>
            </tr>
            </table>
           </div>
          <div class ="date_right">
           <h3 style="border-bottom: 1px solid #426579;border-left: 10px solid  #995588;padding: 7px; margin: 3px;">目標</h3>

          <%= bar_chart [['目標', 7], ['契約数', 3]],id: "col-chart", width: "300px", height: "200px", colors: ["#D199FF", "#FFBA66", "#666"] %>
          <div class="right">
           <div class="java">
            <script language="JavaScript"><!--
              StartDay="2021/10/1";  
                setDay=new Date();
                targetDay=new Date(StartDay);
                pass =Math.floor((setDay-targetDay)/1000/60/60/24);
                document.write("10月に入ってから【");
                document.write(pass);
                document.write("】日経過！！");
            </script>
             </div>
            <table class="right_table">  
            <tr>
              <th class="right__col1">今月の目標期限</th>
              <td class="right__col2">
              <script Language="JavaScript">
                function xDay(y,m,d)
                {
	                today = new Date();
	                xday  = new Date(y,m-1,d);
	                dayMS = 24*60*60*1000;
	                n = Math.floor((xday.getTime()-today.getTime())/dayMS)+1;
	                document.write(n);
                  }
                </script>
                  残り
                <script language="JavaScript">
                  xDay(2021,10,31);
                  </script>
                  日
              </td>
            </tr>
             <tr>
              <th class="right__col1">今月の目標数</th>
              <td class="right__col2">【7】件</td>
            </tr>
            <tr>
              <th class="right__col1">現在の契約数</th>
              <td class="right__col2">【5】件</td>
            </tr>
            </table>
          </div>
        </div>
      </div>
      <h3 style="border-bottom: 1px solid #426579;border-left: 10px solid #426579;padding: 7px;">商談一覧</h3>
         <div class="card__wrapper">
         
         <%= render partial: 'opportunity', collection: @opportunities %>

    </div>
   </div>
   <% else %>
       <%= image_tag 'p.png' %>
   <% end %>

  </div>
</main>

app/views/opportunities/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">商談登録</h2>

      <%= form_with model:@opportunity, local: true do |f| %>
         <%= render 'layouts/error_messages', model: f.object %>

        <div class="field">
          <%= f.label :title, "タイトル" %><br />
          <%= f.text_area :title,class: :form__text %>
        </div>

         <div class="field">
          <%= f.label :phase_id, "商談フェーズ" %><br />
          <%= f.collection_select(:phase_id,Phase.all, :id, :name, {}, {class:"select-box"}) %>
        </div>

         <div class="field">
          <%= f.label :motivation_id, "熱さレベル" %><br />
          <%= f.collection_select(:motivation_id,Motivation.all, :id, :name, {}, {class:"select-box"}) %>
        </div>

        <div class="field">
          <%= f.label :bottle_neck, "ネックになっている事" %><br />
          <%= f.text_area :bottle_neck, class: :form__text %>
        </div>

        <div class="field">
          <%= f.label :next_action, "次のアクション" %><br />
          <%= f.text_area :next_action, class: :form__text %>
        </div>

        <div class="actions">
          <%= f.submit "新規登録", class: :form__btn  %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/opportunities/show.html.erb
<main class="main">
 <div class="wrapper">

        <div class="chat-side">
          <%= render partial: "side_bar" %>
        </div>

      <div class="demo">
       <div class="demo__wrapper">
          <table class="demo_table">

          <div class="demo__hedding">
              <P class="demo_text">詳細ページ</p>
               <% if current_user == @opportunity.user%>
                 <div class="demo__btn">
                <%= link_to "編集する",  edit_opportunity_path(@opportunity),class: :demo__btn %>
               <% end %>  
             </div>
          </div>
              <th class="demo__name1">投稿者</th>
              <td class="demo__name2"><%= current_user.name%></td>
            </tr>
            <tr>
              <th class="demo__name1">投稿日時</th>
              <td class="demo__name2"><%= @opportunity.created_at.strftime('%Y年%m月%d日') %></td>
            </tr>
        <table class="demo_table">
          <p class="demo__text2">商談の詳細</p>
             <tr>
              <th class="demo__col1">商談名</th>
              <td class="demo__col2"><%= @opportunity.title %></td>
            </tr>
            <tr>
              <th class="demo__col1">商談フェーズ</th>
              <td class="demo__col2"><%= @opportunity.phase.name%></td>
            </tr>
            <tr>
              <th class="demo__col1">熱さ</th>
              <td class="demo__col2"><%= @opportunity.motivation.name %></td>
            </tr>
            <tr>
              <th class="demo__col1">ネックになっている事</th>
              <td class="demo__col2"><%= @opportunity.bottle_neck %></td>
            </tr>
            <tr>
              <th class="demo__col1">次のアクション</th>
              <td class="demo__col2"><%= @opportunity.next_action %></td>
            </tr>
          </table>
          <table class="demo_table">
           <p class="demo__text2">対応進捗</p>
            <tr>
              <th class="demo__col1">初回からの経過日数</th>
              <td class="demo__col2"></td>
            </tr>
            <tr>
              <th class="demo__col1">初回日時</th>
              <td class="demo__col2"><%= @opportunity.created_at.strftime('%Y年%m月%d日')%></td>
            </tr>
            <tr>
              <th class="demo__col1">初回内容</th>
              <td class="demo__col2"><%= @opportunity.bottle_neck %></td>
            </tr>
            <tr>
              <th class="demo__col1">ネックになっている事</th>
              <td class="demo__col2"><%= @opportunity.bottle_neck %></td>
            </tr>
            <tr>
              <th class="demo__col1">次のアクション</th>
              <td class="demo__col2"><%= @opportunity.next_action %></td>
            </tr>
          </table>
        </div>  
      </div>  

          <div class="comment">
            <div class="comment__wrapper">
              <p class="comment__title">comment</p>
               <% if user_signed_in? %>
                <%= form_with model: [@opportunity, @comment], local: true do |f|%>
                  <%= render 'layouts/error_messages', model: f.object %>
                   <div class="kind_field">
                     <%= f.label :kind_id, "コメント種類" %><br />
                     <%= f.collection_select(:kind_id, Kind.all, :id, :name, {}, {class:"select-box"}) %>
                   </div>
                   <div class="comment_field">
                     <%= f.text_area :text, size: "70x4", class: "form-control" ,placeholder:"アドバイスやフィードバックコメントを入力してください" %>
                   </div>

                    <div class="actions">
                      <%= f.submit "コメントする", class: :comment__btn %>
                    </div>
                  <% end %> 
                 <% end %> 
             </div>

              <div class="comment__main">
                <ul class="comments_lists">
                  <% @comments.each do |comment| %>
                   <div class="comments_list">
                    <div class="balloon1">                    
                     <div class="icon">
                       <%= image_tag comment.user.image, class: :side__image %>
                        </div>
                          <div class = "comment_kind" >
                            <%= link_to "#{comment.user.name}さんからの", user_path(comment.user), class: :comment_user %>
                              <%= comment.kind.name %>
                             </div>
                              <%= comment.text %>
                             </div>
                            <%= link_to "#{comment.user.name}", user_path(comment.user), class: :comment_user %>
                          <td><%= comment.created_at.strftime('%m月%d日   %H:%M') %></td>
                        <% end %>
                       </ul>
                   </div>
             
  </div>  
</main>

app/views/users/show.html.erb
<div class="main">
    <div class="user__wrapper">
      <div class="user__image">
        <%= image_tag @user.image %>
          <h2 class="user-heading">
          <%= "#{@user.name}さんの情報"%>
         </h2>
         <div class="user__btn">
          <%= link_to "編集する",  class: :user__btn %>
        </div>
        </div>
      <table class="table">
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @user.name %></td>
          </tr>
          <tr>
            <th class="table__col1">プロフィール</th>
            <td class="table__col2"><%= @user.profile %></td>
          </tr>
          <tr>
            <th class="table__col1">役職</th>
            <td class="table__col2"><%=  @user.position %></td>
          </tr>
      </table>
      </div>
    </div>
  </div>